### ISSUE TITLE
Internal notifications system

### ISSUE THREAD

**Issue by ionparticle** [ubc/compair#106]
Can be from instructor to student only initially. The original use case was for instructors/TAs to provide private feedback to a student.

**Comment by lenglund** [comment]
As discussed, here are the basics of the notifications system.

Students: notified of 1) new questions/assignments posted in classes they are enrolled in, 2) replies (public and private) to answers they have posted, and 3) comments left for questions they have previously posted comments in.

Instructors: notified of 1) the end of any answer/comparison period for questions in their courses (with quick stats), 2) any replies to answers they have posted, 3) answers that have been flagged for questions in their courses, and 4) comments left for questions in their courses.

New questions: notification happens once per question, link takes user to question screen
New replies: notification happens once per answer (and notes total number of new replies), link takes user to question screen with user's answer filtered and toggle for replies open
New comments: notification happens once per question (and notes total number of new comments), link takes user to question screen with help tab selected
New flagged answer: notification happens once per answer, link takes user to question screen with flagged user filtered
New completed period: notification happens once per period (and notes quick stats, e.g., # answered vs. # students enrolled), link takes user to question screen (if answer period) or comparisons screen (if comparison period)

Notifications need to be clicked on to be dismissed. We may also want to include a way to dismiss all.

**Comment by lenglund** [comment]
Should students be notified if their answer gets flagged?

**Comment by lenglund** [comment]
Students also requested this from the second Physics pilot.
