### ISSUE TITLE
Allow TAs see students' personal information

### ISSUE THREAD

**Issue by mwytang** [ubc/compair#172]
TAs can see students' first names and last names on other screens including the participation screen, so it makes sense for them to see the same information on the students' user profiles. Currently TAs cannot see this, but instructors can because the permissions is based on the ability to edit enrolment. 

A possible solution is to change the function to check for the ability to READ enrolment, which will includes TAs.

**Comment by lenglund** [comment]
This makes sense for consistency, but I don't think it requires resolution (no problem to solve).
