### ISSUE TITLE
Option to hide scores and student names for instructors/TAs

### ISSUE THREAD

**Issue by mwytang** [ubc/compair#186]
This allows instructors to display submitted answers to the students without showing the associated scores or student names.

We could add this as an option in the filter dropdowns that already exist on the question screen.

**Comment by lenglund** [comment]
Teaching assistants reported an interest in doing this as well during the survey/focus group.

**Comment by lenglund** [comment]
In reviewing this, it seems like the filter option is not the best solution for the use case proposed. If an instructor/TA wants to highlight a good/poor answer in a class of 150, for instance, it would be hard to locate that answer if the other filters can't be used along with this option. I am changing this to a checkbox option that can be used in conjunction with other filters.

**Comment by lenglund** [comment]
Updated in 8528b599a26bf0f9c7852cdab7b5d08916ccb8e9. Need to look at tests.

**Comment by andrew-gardener** [comment]
@lenglund just need you to check the UI change I made in 54c77dda6b2dbe238f20cd108e26b94c2b6008d9 (switched from checkbox to toggle button) which was merged in #457

**Comment by lenglund** [comment]
Thanks! Updated in 01c1c8460da9fcc8eb8d09bd7cf1937920aa38a1.
