### ISSUE TITLE
Add screen for admins to manage users on a global level

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#191]
Provide a way for admins to see/filter through all users in the system and make changes to the users' information and enrolments. This would require a new admin-only interface.

This could be a navigation item in the admin bar that appears just for admins.

**Comment by lenglund** [comment]
Think about what the interface would look like for managing users globally.

**Comment by lenglund** [comment]
Consider how to use similar approach to class list.

**Comment by lenglund** [comment]
Admins should also be able to see who created and/or is instructor/TA for each course.

**Comment by lenglund** [comment]
Relates to #472.

**Comment by andrew-gardener** [comment]
Separated ability to activate/deactivate user accounts into another issue (#487)
