### ISSUE TITLE
Ability to release really good answers/comparisons

### ISSUE THREAD

**Issue by mwytang** [ubc/compair#201]
Instructors would like to have the ability to release good answers/comparisons to class so that they can learn from them and do better in the next iteration.

**Comment by lenglund** [comment]
This seems problematic from a privacy standpoint, since we explicitly tell students their comparisons are private when they write them. If this feature is implemented, we will also have to update the wording/explanation for the comparison boxes to warn users their submissions may be made public by instructors.

**Comment by mwytang** [comment]
This idea was mentioned in passing. I've created this issue merely to document that the idea was mentioned, and there are no plans to implement it. Therefore, it is marked for 'Later'.

**Comment by lenglund** [comment]
No worries, I am simply noting that we'll have to consider how we communicate the situation to student users, if this change is made. =)

**Comment by lenglund** [comment]
Students in surveys also indicated some interest in seeing "best" answers as selected by an instructor or TA.

**Comment by lenglund** [comment]
Best approach here would be to:
- [ ] Add a way for instructors/TAs to mark an answer as one of the top answers
- [ ] Add a filter for anyone to use that shows the top answers only (by submission date?)

**Comment by andrew-gardener** [comment]
#411 Handles the back-end with a bit of UI for the front-end just to get it started

I used a filled-in/empty star icon for instructors to use to toggle the top answers (currently only displays in the 'answers' tab on the assignment screen) and added a basic checkbox filter for filtering the answers by top answers which only appears when there is at least one top answer (assignment.top_answers_count)

**Comment by lenglund** [comment]
UI review completed in 70b5b7385c0c90ce4f5e489f826e687b1dc95337.

Would it be possible to instantly remove "un-starred" answers when I'm viewing the top answers filter (i.e., update the answer count and remove the answer from the list)?

**Comment by andrew-gardener** [comment]
https://github.com/ubc/compair/commit/00dd4dbbfc56f93b7c5ec8887f0bc7e3db6da475 updates the answer list when an answer is un-starred while filtering by top answers

**Comment by lenglund** [comment]
Completed with 00dd4dbbfc56f93b7c5ec8887f0bc7e3db6da475.
