### ISSUE TITLE
Allow instructor answers to be included in comparisons

### ISSUE THREAD

**Issue by xcompass** [ubc/compair#251]
This would be incredibly useful for calibration. - James

**Comment by lenglund** [comment]
If this feature is implemented, it would need to be a checkbox for the answer (to include or not include it in the answer pool).

**Comment by andrew-gardener** [comment]
toggle between `post as instructor's answer (not compared)` or `post as a student answer (compared)`
- consider answers appearing as student answers or labeled as instructor answers (optional toggle, default one or the other, etc)

**Comment by lenglund** [comment]
This was mentioned at the brown bag echoing James's sentiment that it would help provide a benchmark ("how did the student rank/respond to my [instructor] answer?").

**Comment by kitsook** [comment]
@xcompass @lenglund Some implications to consider.

*How will instructors benchmark the comparison result?*
- Enhance the existing reports to include instructor answers?
- Current participation reports are student based (one row per student).  Multiple rows need to be shown for instructor if he entered multiple answers.  Also need additional columns to identify the answer (e.g. extract the first 100 characters of the answer and trim any line break and comma?  what if the answer only has attachment and no text?).
- Or, create a new report just for instructor answers

*Enough answer to compare?*
- With instructor's (multiple) answers mixed in the comparison pool, there will be enough number of answer to start comparison after the first student answered.
- e.g. With multiple instructor answers, after the first student answered the assignment, the existing course / assignment page will show `Not enough answers to compare right now`.  Yet, the student can click on the seemingly disabled `Compare Pairs` button and start comparing instructor's answers.
- Need to unify the logic on displaying `Not enough answers to compare right now` vs number of answers available to compare (when counting multiple answers from the same instructor).
- Impact should be low if comparison period doesn't overlap with answering period

**Comment by lenglund** [comment]
Re: report
Definitely we want to include instructor answers in the student report. Adding a student/instructor column could also help. I like the idea of the snippet for the answer.

Re: enough answers
Students can't compare their own answer, so there would have to be two instructor answers in the pool first. I don't think it matters to let students compare these?

**Comment by kitsook** [comment]
```
Re: enough answers
Students can't compare their own answer, so there would have to be two instructor answers in the pool first. I don't think it matters to let students compare these?
```
True that students can't compare their own answer.  But currently there is no rule preventing comparison of two answers from the same person.  So if the instructor has created multiple answers, the first student who answered the assignment could also start the comparison and ended up comparing different answers from the same instructor.

This should be a rare case as it will only happen if answering period overlaps with comparing period.  And if the instructor created multiple answers, it is expected that those answers will be compared against each other.

**Comment by xcompass** [comment]
I don't think it matters. It is also a kind of calibration. Also we need at least three answers in the pool for student to do 3 comparisons.

**Comment by kitsook** [comment]
Referring to the reports.  The existing "Basic Participation Report" allows inclusion of multiple assignments.  One student per row with assignment statistics listed across columns.  Probably not a good report to include comparison result of instructor answers.  Instructors could be creating multiple answers per assignment.

Will create a new report similar to "Participation Report for Research Teams" with answer snippet and scores etc. for each answer
