### ISSUE TITLE
Consider analytics wanted from system

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#264]
List to be generated during discussion with ACJ working group. Starts issue #240.

**Comment by lenglund** [comment]
Notes from group dialogue:
- We want to record at a text-field level, e.g., not for every keystroke but for every action/command on the screen
- Record when an event happens, what the event was, what the status was of the thing being acted on
- Need enough data to compute how long students spend on different pages, how long they spend on activities, when they changed inputs, etc.
- Save every event as well as the state of the content (so will need drafts of answers and comparisons behind-the-scenes)
- There could be an impact on performance, so need to be careful of how we implement
- Data just for researchers for now and will be part of the downloads
- Future consideration for a new UI to view the more important stats
- Participation is most important for real time (UI) display and this is already there
- Would be good to also communicate if a student hasn’t spent much time, some way to show instructor that student is "blowing off" the assignment (e.g., maybe time spent on page or amount of content typed)
- Dev team to map out what data to collect based on screen accessed

**Comment by lenglund** [comment]
Some complexity to consider re: files uploaded and saving different versions of these, if students make changes.

**Comment by andrew-gardener** [comment]
Capturing information completed in #441

Remaining tasks:
- [ ] finalize verb, activity, and extension resource identifier (waiting on response from Tincan registry)
- [ ] finalize profile

**Comment by andrew-gardener** [comment]
Remaining tasks to be completed in #467 and #466
