### ISSUE TITLE
Comparison example feedback

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/compair#314]
Ido brought up an enhancement for comparison examples for a future version. 

Instructors should be able to set feedback for comparison examples based on the student's choice for each criterion.

Requires adding a new screen after a comparison example has been evaluated to give the student the feedback.

**Comment by lenglund** [comment]
Request on hold until we see if/how comparison examples are used.

**Comment by lenglund** [comment]
Interest expressed for this at the brown bag session.
