### ISSUE TITLE
Adding grade

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#316]
As part of LTI integration (#263), grades can be sent. But we first need to add grading to the application. Preference is to set this at the course level, with options to set percentages for: 1) student submitted answers, 2) student completed evaluations, and 3) student final answer score (may need to be by criteria).

**Comment by xcompass** [comment]
again, not on assignment level?

**Comment by lenglund** [comment]
Correct. If I understand what @andrew-gardener explained in the meeting today, the current integration version we're aiming for only allows one grade to be passed (at the course level). This is how Ido suggests we do it to accommodate.

**Comment by andrew-gardener** [comment]
We can still have custom grade weighting for each assignment. 

I believe that LTI 1.1 only allows one [0, 1] decimal grade to be passed back per context id (course) though so we need to sum assignment grades together in some way (average grade/assignments, different weighting/assignment, etc)

**Comment by xcompass** [comment]
> I believe that LTI 1.1 only allows one [0, 1] decimal grade to be passed back per context id (course) 

This is not true. A grade is identified by lis_result_sourcedid from the launch request. It is unique for each user_id / resource_link_id combination. And a resource_link_id is an unique identifier that the TC guarantees will be unique within the TC for every placement of the link. So in theory, if an instructor places two LTI links in LMS, there should be two unique lis_result_sourcedid strings recorded in TP. This allows instructor to place different assignments into different section in LMS. And it will result different columns in the gradebook when the grades are passed back.

I think we should to allow instructor to have individual grades from different assignments from ComPAIR and they can do whatever weighting or calculation themselves in LMS for the final grades.

/cc @jleong-openedx for his reference

**Comment by lenglund** [comment]
Need instructor input on how assignment grading would work. How to set the grade? Maybe we can start with percentage for answer (if completed) and for comparisons (if completed).

**Comment by andrew-gardener** [comment]
Basic LTI outcome functionality checklist
- [ ] Add LTI grade to back-end
- [ ] Send grade on answer submitted
- [ ] Send grade on each comparison submitted
- [ ] Send grade on self-evaluation submitted

**Comment by lenglund** [comment]
Updated in 3de8c6b7fb85a71e52ee0223c858acfdd837a650. (Need to look at tests.)

@andrew-gardener, can you hook up back end for branch 0.9.x-Continue-#316?

I can revisit after...
