### ISSUE TITLE
Chosen for long select lists

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/compair#375]
Consider using Chosen library for long select lists. ex: filtering answers or grade book results by a student's name in a class of 100+

https://harvesthq.github.io/chosen/
https://github.com/leocaseiro/angular-chosen

**Comment by xcompass** [comment]
Looks good to me 👍

**Comment by lenglund** [comment]
Nice!

**Comment by andrew-gardener** [comment]
@lenglund please review UI changes when you get a chance

**Comment by lenglund** [comment]
Great suggestion, thanks! Reviewed in 1b36c7ae22f6f061053ae8047002382df546bc0f.
