### ISSUE TITLE
Allow teaching assistants to do comparisons

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#380]
Enable teaching assistants to complete comparisons just like students, primarily for research purposes.

**Comment by andrew-gardener** [comment]
Would it make sense to allow instructors as well?

**Comment by xcompass** [comment]
yes. instructors and TAs.

**Comment by lenglund** [comment]
Not sure how this was implemented, but I think it is preferable to have this be a setting on the assignment side. If instructors/TAs won't be doing comparisons (which will be the majority of use cases), we don't want to clutter up the UI with lots of "Compare Answers" buttons...

**Comment by andrew-gardener** [comment]
#393 adds the option to turn comparisons on/off for instructors and teaching assistants

**Comment by andrew-gardener** [comment]
@lenglund please go over the UI changes when you get a chance 
- New option in assignment form (bellow self evaluation toggle)
- 'Compare Answers' buttons for instructors + teaching assistants on the assignment list and assignment view screens
- Slightly adjusted comparison screen for instructors + teaching assistants so they see the round count only (not round/total)

**Comment by lenglund** [comment]
Reviewed in c0c0daca5411271bf77aaacde1b766b71c8a91b4.
