### ISSUE TITLE
Consider preliminary notifications

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#381]
Add displays of messages related to #106 without using messaging system initially.

**Comment by lenglund** [comment]
Relates to #290.

**Comment by lenglund** [comment]
First phase will be email only.
- Notify students of: new answer replies (to their answer)
- Notify instructors of: new assignment help comments

**Comment by andrew-gardener** [comment]
do we want to do a daily digest email format or send one one email for each event?

**Comment by xcompass** [comment]
For the simplicity, I think we should do per event for now.
