### ISSUE TITLE
button seprators are mis-aligned on user manage page

### ISSUE THREAD

**Issue by xcompass** [ubc/compair#392]
<img width="109" alt="screen shot 2016-09-20 at 11 40 16" src="https://cloud.githubusercontent.com/assets/465548/18683936/2e3c017e-7f27-11e6-8843-0ad7ad1876d0.png">

**Comment by lenglund** [comment]
What was the context for this screenshot (device/browser)?

**Comment by lenglund** [comment]
Should be fixed in eb56867a90e607830641c4617b1c713e4f354353.
