### ISSUE TITLE
Create and add logo

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#430]
Includes adding favicon, home nav item, home page image, comparison page image, website favicon/images.

Note:
`src="/app/img/<img name>"`

**Comment by lenglund** [comment]
Full logo, first draft. Feedback encouraged!
![compair-pear](https://cloud.githubusercontent.com/assets/6118592/20533129/5878e830-b091-11e6-9bfd-6f33c300e316.png)

**Comment by xcompass** [comment]
How does it look in smaller size? e.g. favicon?

**Comment by lenglund** [comment]
32 x 32, with and without thought bubbles:
![compair-pear-fav](https://cloud.githubusercontent.com/assets/6118592/20538521/7c17137e-b0a6-11e6-93c6-880280d02cf0.png)
![compair-pear-fav-2](https://cloud.githubusercontent.com/assets/6118592/20538522/7c18a93c-b0a6-11e6-862e-7089939aa312.png)

**Comment by xcompass** [comment]
like the one with bubble

**Comment by lenglund** [comment]
Let's discuss logo goals and revisit for next version.

**Comment by lenglund** [comment]
An idea:
![compair-logo](https://user-images.githubusercontent.com/6118592/27977730-eb267bd8-6320-11e7-8bd2-5680a5af565b.png)

@xcompass, @andrew-gardener - Thoughts?

**Comment by andrew-gardener** [comment]
- Like the idea of a balance to help represent comparing pairs. 
- Green is always a + (for me)
- I don't like the line sticking out of the center of the balance
- I don't like the balance sticking out of the "PAIR" for some reason

Maybe something like this (quick dirty edit):
![27977730-eb267bd8-6320-11e7-8bd2-5680a5af565b copy](https://user-images.githubusercontent.com/3082802/27978502-9e68ac40-6324-11e7-9d45-8550e66a7d63.png)

or have everything on the same level "ComPAIR [balance]"

**Comment by xcompass** [comment]
Looks good!

**Comment by lenglund** [comment]
Final (for now):
![compair-logo-large](https://user-images.githubusercontent.com/6118592/28142266-f7ec8662-6714-11e7-9786-3de1e52d9034.png)
