### ISSUE TITLE
Minor updates to instructor workflow

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#432]
Consider observations from instructor setup session:

- "Do I change this?" re: display name in account setup
- Term/Semester unclear what to input (letter? number? both? also an issue in prod)
- "This is for the whole course?" re: dates in course form
- "I can attach my own directions?" re: attach PDF
- "Answering means submitting an assignment?" re: answer dates
- Is form understandable without intro text (check labels)?
- Preview button easy to overlook in intro text
- Clicking outside pop-up closes form without saving
- "Can you alter this?" re: feedback section in preview
- Allow instructor/TA to compare unclear, maybe "Allow instructors/TAs to participate..." instead?
- "Are students anonymous?" re: discussion section (now renamed and moved)
- "How do I see what they see again?" re: finding preview button after editing
- Unclear if instructor's answer enters the comparison pool

Also comments on report:
- "Is 'Percentage score' the percentage of positive comparisons each answer got for each 
criterion?"
- Evaluations submitted confused for evaluations done on the answer

**Comment by lenglund** [comment]
Work dependent on merging prior branches involving assignment form.

**Comment by andrew-gardener** [comment]
handle clicking outside of modal (don't auto close modal)

**Comment by lenglund** [comment]
Updates made in 6909ec527a886a25ef03536a062c11014877164d.
