### ISSUE TITLE
Edit Course end/start dates using UTC

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/compair#445]
A instructor using sandbox reported that course start/end times are using UTC when editing them. 

This doesn't appear to be happening on production so was likely introduced via changes in the 0.9.x branch.

**Comment by xcompass** [comment]
Both servers' time zone are setup to PST.

**Comment by andrew-gardener** [comment]
Seems to be caused from my commit https://github.com/ubc/compair/commit/b46f1c95c39e44bd50ce11dbc33446c3e87c41bd. Flask Restful was not sending timezone info for iso 8601 format when accessing the field directly.
