### ISSUE TITLE
Consider way to extract/visualize xAPI data

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/compair#467]
Continues data extraction aspect of #264

Specifically (https://github.com/ubc/compair/issues/264#issuecomment-240862046)
- Data just for researchers for now and will be part of the downloads
- Future consideration for a new UI to view the more important stats
- Participation is most important for real time (UI) display and this is already there
- Would be good to also communicate if a student hasn’t spent much time, some way to show instructor that student is "blowing off" the assignment (e.g., maybe time spent on page or amount of content typed)

**Comment by lenglund** [comment]
Would be good to discuss this with the wider team before moving forward.

**Comment by andrew-gardener** [comment]
do #550 first

**Comment by xcompass** [comment]
#612
