### ISSUE TITLE
Restructure permissions data endpoint

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/compair#468]
Started receiving cookie size warnings: 
`Cookie 'current.permissions' possibly not set or overflowed because it was too large (4234 > 4096 bytes)!`

Very likely that this is happening due to uuid size (22 characters each). 

Restructuring permissions can reduce the likely hood of going over the limit.

**Comment by xcompass** [comment]
Looks like it is better to trim it down to 4096 for browser compatibility: http://stackoverflow.com/questions/640938/what-is-the-maximum-size-of-a-web-browsers-cookies-key

We may solve this issue by switching to JWT and store permission and other info in the token.

**Comment by andrew-gardener** [comment]
Decided to move to using browser's local storage (fallback cookies) to store data like permissions on the front-end.

@xcompass JWT would be a pretty good alternative login management (#249) but wouldn't solve persisting permission data for the front-end to use since it would all be encrypted (currently permissions endpoint is used for controlling which ui elements to display in the views).
