### ISSUE TITLE
Improve media attachment integration

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/compair#470]
Add way to view all attachments inline

In particular video and audio playback. 
Also look into other services for hosting attachments.

**Comment by lenglund** [comment]
Look at Kaltura.

**Comment by xcompass** [comment]
This issue is brought up again during the Arts workshop. We also need to figure out a way to securely embed video in the assignments/answers.

**Comment by andrew-gardener** [comment]
@lenglund Please have a look at the 1.0.x-#470 branch when you get a chance. The UI that I created for displaying the attachments & external resources inline needs some love. I can help set you up with my Kaltura demo account as well
