### ISSUE TITLE
Add Admin LTI consumer management screen

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/compair#472]
Screen needs to be able to create, edit, and deactivate/reactivate LTI consumers

**Comment by lenglund** [comment]
Again, any way to hide the breadcrumb or disable the link to the "ComPAIR Setup"?

**Comment by lenglund** [comment]
Admin bar has a typo "Comsumers" instead of "Consumers". I assume this is terminology we feel admins will understand?

**Comment by lenglund** [comment]
Really need to rethink the admin bar as part of #471.

**Comment by lenglund** [comment]
Admin bar should follow naming convention and have a verb, e.g., "Manage LTI" or "Manage Consumers" or something similar.

**Comment by lenglund** [comment]
The trailing "|" can be removed for actions.

**Comment by lenglund** [comment]
I suggest changing the column name from "Active" to "Status".

**Comment by lenglund** [comment]
Only other question is whether this is enough information for an admin to know what the key/secret is for? In other words, does this give me enough detail to determine if I want the status to be active or not? Or is there more we would want to give for details (e.g., adding a consumer name to the form)?

**Comment by andrew-gardener** [comment]
I don't think we need to add any more information to the form. Technically the admin could use the key as a identifying name for the consumer if they wanted to keep track of them that way.

I updated the readme file (in the pull request) with some basic instructions to create a LTI consumer. I think admins would have enough knowledge of LTI beforehand to not be confused by the settings and admins without knowledge might just disable LTI (which will make the 'Manage LTI' button not appear for them).
