### ISSUE TITLE
Create external sandbox

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#486]
Set up a demo instance and post demo accounts for people to test out the application.

**Comment by andrew-gardener** [comment]
- [ ] create initial db data (should allow users to see all parts of the application

**Comment by xcompass** [comment]
Demo instance is live at http://compairdemo.ctlt.ubc.ca now!

**Comment by xcompass** [comment]
Note that demo instance is tracking master branch and will be updated on every push to master. It also reset the database at 3am.
