### ISSUE TITLE
Add pair selection algorithm based on multidimentional scaling 

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/compair#500]
Calculate minimum delta between criteria scores when multiple criteria are used (pairing algorithm, need to keep criteria weight in mind)

**Comment by kitsook** [comment]
@andrew-gardener i am thinking to keep the existing generate_pair function parameter list.  instead a new dictionary field will be added to the ScoredObject to store the criteria-based scores and weights.  any thoughts?

also, i am looking at the answer_criterion_score table for the criteria-based scores.  is it the right place?  i ran a few comparison locally on docker and found the rounds/wins/loses values a bit funny.

**Comment by andrew-gardener** [comment]
@kitsook I think it would be better to create a new folder and algorithm so we have the old pairing function for reference and legacy usage. To do this you will need to add a new pairing algorithm in the enum and update the `pairing_algorithm` column in assignment (https://github.com/ubc/compair/blob/master/compair/models/custom_types/pairing_algorithm.py) 

You can continue using ScoredObject and just pass the dictionary of criteria scores into `score` field for each answer and add a comment stating that assumption in the algorithm. You can also pass in the criteria weights as a new parameter (https://github.com/ubc/compair/blob/master/compair/algorithms/pair/core.py#L3 uses `**kargs` so you can add whatever additional params are needed to work out the algorithm). I'd prefer not changing ScoredObject as its also used by the scoring algorithms.

yes, the criteria based scoring is currently in `answer_criterion_score`. The overall winner scoring (using the weighted criteria selections to decide winner allowing ties) is in the `answer_score` table. 

The only expected weirdness with the rounds/wins/loses that I can think of would be that as soon as a student is assigned a pair of answers, we increment the round for both those answers so that the answers are not assigned to another student in that comparison round (since answering comparisons can take time and we don't want answers to be assigned more expected when its close to the end of a round). If your noticing something other than that, let me know as it might be  a bug.
