### ISSUE TITLE
Allow admin to create/delete third party logins

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/compair#517]
Add create/edit lti + cas form for admins and place to view and delete existing lti + cas logins

**Comment by andrew-gardener** [comment]
need to consider exact functionality

**Comment by wynnset** [comment]
@andrew-gardener if this is something I can work on, can we please review it together?

**Comment by wynnset** [comment]
@andrew-gardener this will probably not get done for this release. I think we should move it into the next release. @lenglund you might want to make sure this is **not** added to the release notes.

**Comment by andrew-gardener** [comment]
This would be very helpful to admin to get in asap in the new term if it cannot be completed for 1.1 (added it to 1.1.1 milestone)

**Comment by wynnset** [comment]
@andrew-gardener the core functionality is now in, so admins can list and delete third party users, and list and unlink LTI users.

Remaining: 
- [ ] Add event tracking
- [ ] Add unit tests

You can probably start the review. @andrew-gardener if it's really essential to get this into this release, maybe we can add this in as-is (after reviewing it, of course), and add the unit tests in the next release. Thoughts?

**Comment by andrew-gardener** [comment]
I'll rather wait until its fully complete. The reason I want to get this in as soon as possible into the next term is that it reduces our support load but I would rather it not be rushed
