### ISSUE TITLE
Let instructor/TAs skip comments when comparing

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/compair#534]
Allow instructors/teaching assistants to skip adding comments for each answer when comparing.

Workaround for now would be to generate comments (default text 'Feedback') for each answer before the comparison process begins.

**Comment by lenglund** [comment]
Can be related to the role and does not need to be a separate flag (i.e., if instructor/TA is comparing, feedback is optional AND does not have a required asterisk).
