### ISSUE TITLE
Double-check course sorting

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#537]
Sort homepage by course start date or, if no course start date, earliest assignment date. Basically, try to put the courses in order by date so it's easier for instructors to find their latest course.

**Comment by andrew-gardener** [comment]
@lenglund Think I found the issue. It didn't handle the case where a course didn't have a start date and had no assignments. 

I've made it so now it will use (in order of priority):
- course start date
- min assignment answer start date
- created date
