### ISSUE TITLE
Move comparisons to a tab on assignment screen

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#540]
Rationale:
Courses contain assignments. Assignments contain outcomes. Yet comparisons sit on a separate screen from everything else (answers list, help comments, participation). I think it makes sense to fold these in and would provide instructors access to everything in one place. This would also allow us better consistency with the use of the green action buttons and would let us consistently link from the assignment counts on the course page, which I'd like to do (taking the user to the associated tab), as shown below.

![assignment-w-links](https://user-images.githubusercontent.com/6118592/28090593-a81c21de-6641-11e7-8a2e-2149e66c9002.png)

**Comment by lenglund** [comment]
No priority assigned for now; @andrew-gardener to work on for this version if he has time.

**Comment by lenglund** [comment]
Will need to consider how this changes the print view, since ENGL TAs had/have a use case that involves printing out the answers + comparisons per student.

**Comment by andrew-gardener** [comment]
fb64ab0f6f2d08e011c31d2cb141b92025f9e07d begins this work (added comparison tab but kept the "see Comparisons" button with old page). Will complete this after we have discussion on what to do about printer friendly view
