### ISSUE TITLE
Move password update into modal

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#544]
Can we move the password update (when it's present) from the bottom of the user edit form so it instead opens in a modal (by clicking on the blue link as shown below)?

![alt-login](https://user-images.githubusercontent.com/6118592/28440316-96f65102-6d5a-11e7-86fb-ada1e1b1f7fd.png)

This would be more consistent with how we show forms and structure pages everywhere else.

**Comment by xcompass** [comment]
I would like to avoid using modal as it is not mobile friendly. Can we do it in a separate view instead?

**Comment by lenglund** [comment]
I assume we'll fix the modal view, so either we'll continue using it with a mobile-friendly workaround or else we'll change everything.

**Comment by andrew-gardener** [comment]
I believe that my mobile modal solution should be good enough that we don't have to avoid modals #559

**Comment by xcompass** [comment]
I think it is tricky to get modal on mobile perfect. If it is good enough then I'm OK with it.

**Comment by wynnset** [comment]
> This would be more consistent with how we show forms and structure pages everywhere else.

@lenglund / @andrew-gardener  can you give an example of somewhere in the application where we are using a similar UI for a form?

**Comment by lenglund** [comment]
If you are logged in as an admin or instructor, add/edit an assignment and add a criterion to that assignment.
