### ISSUE TITLE
Re-address mobile view

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#547]
Style changes require re-visiting small screen displays

**Comment by lenglund** [comment]
Download xcode.

**Comment by lenglund** [comment]
Menu label for mobile navigation.

**Comment by lenglund** [comment]
Going a little crazy trying to stop to auto-zoom for the rich text editor. I don't think this is a deal-breaker (i.e., it's not overly disruptive to the user workflow) but it is annoying.

**Comment by andrew-gardener** [comment]
https://stackoverflow.com/a/39291806

Looks like we can do this with: `CKEDITOR.addCss(...)`

**Comment by lenglund** [comment]
Thanks, @andrew-gardener! Adding `contentsCss: ["body {font-size: 16px !important}"]` seems to have resolved it.
