### ISSUE TITLE
Revisit grading

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#550]
Meet with instructors to discuss grading and analytics needs

**Comment by wynnset** [comment]
Currently on the individual assignment pages, we have the following columns that are score-related:
- Answer Score
- Evaluations
- Self-Evaluation
- Participation Grade

Would the instructors want to only see the "Answer Score" on this page (per assignment and aggregate) or would they need to see anything else as well (e.g. Participation Grade)? We could also consider creating one tab for Answer Score and another one for Participation? Thoughts @lenglund ?

**Comment by lenglund** [comment]
I think we were going to meet as a group to discuss what this would look like. I'll book a meeting time.

**Comment by lenglund** [comment]
An idea: have the UI provide different options for reporting (similar to how we handle reports), with the option to extract/download each one. With this approach, the information in the UI and reports would be the same (on the course level), so instructors could get a preview of what they would be downloading. We'll start by consulting with instructors who used the app in W1 to see what would be helpful to them (see #612).

**Comment by wynnset** [comment]
@lenglund do you have an answer for my question above yet? :)

**Comment by lenglund** [comment]
I am still interviewing instructors about needs around this and will update this issue or create a new one(s) when that completes (end of Jan). Thx!

**Comment by lenglund** [comment]
Findings resulting from interviews broken out into separate issues.
