### ISSUE TITLE
Review Toaster messages

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#551]
Clean up and add conventions to style guide

**Comment by andrew-gardener** [comment]
search for `Toaster.` (case sensitive) `message=`

**Comment by lenglund** [comment]
"Server error during authentication" especially needs update when password is incorrect.

**Comment by lenglund** [comment]
Work is ready for review in #551-review-messages branch. Not doing a pull request at this time, as it should be technically merged into 1.1, not master...

@andrew-gardener - Could use your double-check on the message text to make sure I'm not saying the wrong thing for the back end errors. Also not sure why the build is failing, as all I've changed is text?
