### ISSUE TITLE
Review conditions for buttons, statuses, and answer tab text

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#554]
What do students/instructors see and when? Do these need to be updated? Can we simplify code by combining these into one template that is then included on the appropriate screens? 

This issue should include:
- [ ] a cleaned-up, reusable way to check the student's status re: answer 
- [ ] a cleaned-up, reusable way to check the student's status re: comparisons/self-eval 
- [ ] using this in place of the complex conditional code currently in use on the home screen, course screen, and assignment screen to control the button, status, and instructional text displayed

**Comment by andrew-gardener** [comment]
- make directive for button group and status
- decide what make sense to have in each area

**Comment by wynnset** [comment]
Hi @lenglund can we go over this together? I'm not sure I fully understand this issue.

**Comment by lenglund** [comment]
Check what state the student is in.

For answer, student will be one of: 
1. need to answer
2. need to finish answer
3. have completed answer
4. can't complete answer (outside the answer period and didn't answer)

For comparison, student will be one of: 
1. need to compare
2. need to finish comparisons
3. need to self-evaluate
4. need to finish self-evaluating
5. have completed all comparisons (including self-evaluation if needed)
6. can't complete more comparisons (outside the comparison period and didn't finish some)
7. can't complete comparisons (outside the comparison period and didn't finish all)

**Comment by andrew-gardener** [comment]
We should consider making common functions that will take in relevant data points (assignment status, etc) and give back the current state to reduce the amount of repeated complex condition checking we are doing throughout the app

**Comment by lenglund** [comment]
For each state, the following need to be looked at.

Home:
1. status of assignment (is it done or is there action the student can take)

Course:
1. status of assignment (what is left to be done: number of answers, number of comparisons)
2. status of completion (what the student has done: answered, compared, potentially how many comparisons)
3. button type and text (what action can be taken: answer, finish answering, compare pairs, finish comparing)

Assignment
1. status of assignment (what is left to be done: number of answers, number of comparisons)
2. status of completion (what the student has done: answered, compared, potentially how many comparisons)
3. button type and text (what action can be taken: answer, finish answering, compare pairs, finish comparing)
4. instructional text (what action can be taken, see above)

**Comment by wynnset** [comment]
Hi everyone @lenglund @andrew-gardener @xcompass ,

I have some suggestions for the status bar that I'd like you to review before proceeding further with this ticket:

![compair-revised-status-bar](https://user-images.githubusercontent.com/8981258/32810692-faffdfcc-c950-11e7-8903-a77f3ecc223f.png)

Here's a few things that are different:
- Admin functions (edit, delete, duplicate) are displayed as icons on their own side
- There's a new status bar for the student to understand how much they have "progressed" in finishing their assignment, along with a status to the side. The letters in each status bar segment represent either "A" for "Answer", "C" for "Compare", or "S" for "Self-evaluate". In this case, the assignments have 3 compares, so there are 3 "C" segments. We can add a tooltip so the student can see what each of those segments mean upon hovering over them.

If necessary, we can run this with users to get some feedback. Looking forward to hear back.

**Comment by lenglund** [comment]
We won't be making major UI changes like this for version 1.1, as anything this large would require revisiting the style guide as well as doing usability testing (neither of which we have time for, given the upcoming release). Could you please limit the changes to cleaning up the code for this issue and reopen a second issue for possible exploration of the proposed UI changes in a later release? I would also like to discuss how these changes relate to the findings from the last round of usability testing before you go further, since we want to be sure we are using the data to inform the design. Thanks!
