### ISSUE TITLE
Allow richer text/media for feedback

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#560]
James reports:

> ...recalling some of the conversations I had with people from WCSE and I just remembered some feedback someone gave. They mentioned that it would be nice if the feedback boxes were as rich as input box. They said that they wanted to be able to upload different media for feedback, rather than just a text feedback.

**Comment by andrew-gardener** [comment]
file meta-data might identify a student

**Comment by lenglund** [comment]
Could start as just adding rich text editor, though it adds bulk to UI (especially on mobile).
