### ISSUE TITLE
Release of 1.0

### ISSUE THREAD

**Issue by xcompass** [ubc/compair#562]
- [x] Write a changelog and release note
- [x] Merge 1.0.x into master
- [x] Tag 1.0 release
- [ ] ~Change the .gitlab.yaml tracking branch~
- [x] Export prod data and test upgrade locally
- [x] Post message to the Google Group

**Comment by lenglund** [comment]
@xcompass, @andrew-gardener, please modify the below as appropriate:

The ComPAIR development team is pleased to announce the release of the official Version 1.0 today.

In addition to back end improvements and upgrades, this version includes:

•	A new location for comparisons, so instructors can view these on the assignment screen alongside answers, help comments, and participation
•	Customizable weights for instructors using multiple criteria on an assignment
•	The ability for instructors to duplicate assignments
•	The option for instructors to customize the instructional text that appears to students prompting the peer feedback portion of the comparison
•	Basic notification emails that, when enabled, let instructors know about new help comments and let students know about new replies to their answer
•	Automatic embedding of certain multimedia URLS, so links from trusted sources appear in answers without having to be clicked (e.g., YouTube videos)
•	Updates to the LTI integration, so ComPAIR can be used at UBC with Canvas
•	A new downloadable report for instructors containing student feedback per assignment
•	A logo and favicon (bookmark image) for the application
•	Improvements to the ComPAIR support site, including the addition of a style guide to keep the application consistent as we grow

**Comment by xcompass** [comment]
@lenglund looks good. I've made the release. Could you send it out? Thanks!
