### ISSUE TITLE
Issue with student_assignment_count on home page

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#587]
What students see as the number of total posted assignments for the course is not always correct. However, what instructors see (assignment_count) is correct. The count students see for unfinished assignments is also correct.

e.g., Course with 4 assignments (two in answer period, one in comparison period, one after both answer/comparison periods) shows as "2 assignments" with "3 unfinished assignments" (correct, as student still needs to answer 2, compare 1) when logged in as a student

#585 depends on resolution

**Comment by andrew-gardener** [comment]
@lenglund I can't seem to reproduce this, can you show me it when you get a chance

**Comment by andrew-gardener** [comment]
Fixed by updating staging
