### ISSUE TITLE
Unable to create a new course through LTI

### ISSUE THREAD

**Issue by xcompass** [ubc/compair#589]
From Rik: 

>  I was playing around, trying to get Connect to create a ComPAIR tool and I got as far as clicking the [Submit and Launch] button on Connect.

> Then I tried to add a new course but ComPAIR wouldn't let me.  But I *was* able to duplicate a course!  I presume I should either be able to do both or neither?  Let me know if you need more information.

**Comment by andrew-gardener** [comment]
Rik's system role is set to `student` for some reason. Need to investigate

**Comment by andrew-gardener** [comment]
#598 will automatically upgrade account system roles to instructor/admin if needed for each LTI launch and when linking linking lti accounts via CAS or applicaiton username/password.

I'm not entirely sure how Rik and one other user ended up with student roles when they should be instructors but I manually fixed them in production for now.
