### ISSUE TITLE
Student rank not made visible

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#593]
Issue with conditional display of parent div where rank was moved to in assignment-view-partial:
`<div class="manager-actions pull-right" ng-if="(canManageAssignment && !answerFilters.anonymous) || (answer.user_id == loggedInUserId && assignment.answer_period && !assignment.compare_period)">`

Conditions need to apply to edit and delete actions; not to display of rank.

**Comment by andrew-gardener** [comment]
Also need to fix some display issues with ranks in student view
