### ISSUE TITLE
Individually created users/teachers don’t end up in the third_party table

### ISSUE THREAD

**Issue by xcompass** [ubc/compair#610]
Reported by St John's school:

> I noticed that individually created users/teachers don’t end up in the third_party table in the ComPAIR database for CAS auth. Bulk created accounts are fine though.

**Comment by andrew-gardener** [comment]
currently there isn't any functionality to add CAS info to individually created users (related to #517)

**Comment by xcompass** [comment]
closing this for now. duplicated #517
