### ISSUE TITLE
Allow groups to affect assignments

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#611]
Use case from Firas:

> Class of 200 will be split up into 2, half the students will get to use ComPAIR in Assignment 2, and the other half will get to use ComPAIR in Assignment 3. We don’t want students in the A3 group to see the ComPAIR questions of A2 but still want everyone to use the same ComPAIR site. Similarly when A3 group is doing ComPAIR, we don’t want A2 students to look at it.

This would mean: making assignments visible only to select groups.

**Comment by lenglund** [comment]
Rik has another use case:

> Each group would make one submission per project stage but I envision every group member  comparing the group submissions.  I'm picturing groups of 3-5, so about 12 groups in a class of 45.  So there would be 12 answers and 45 students comparing them.

Basically this would mean 1) allowing 1 answer per group and 2) removing the group's submissions from comparison by any group member.

**Comment by wynnset** [comment]
I can see 2 ways this could be implemented:
1. The instructor creates a different "course" for each group. That way, everything will be separated by default and students won't be in any way interacting with students in other groups. This option obviously requires no effort from our end in terms of development, but of course, it's not very elegant and I'm guessing also will mean that the instructor can't see a course-wide aggregate data between all groups.
2. We create the concept of groups in Compair and update the logic accordingly. The pros of this option are that the instructor will have better visibility of course-wide aggregate data and it's more elegant. The downside is that it would be quite a bit of work to implement.

Let's discuss this further in the next meeting.

**Comment by lenglund** [comment]
We already have groups in ComPAIR and just need to update the logic.

**Comment by kitsook** [comment]
The course grade calculation logic will be affected.  Will other systems linked with ComPAIR via LTI need to be aware of group-specific assignments?

How to allow group members to collaborate on the answer?  Allow re-submission of the group answer by any group member?

**Comment by xcompass** [comment]
we will focus on first use case first.

**Comment by lenglund** [comment]
First case brought up again in ComPAIR Google group.

**Comment by lenglund** [comment]
Second case brought up by multiple instructors in working group. This is probably more useful for teaching, whereas the other case is more useful potentially for research.

For a first version of group submission, the idea is that an instructor could check group submission as part of the assignment form. Then any student in a group could submit on behalf of the group and see feedback for the group answer. But there are many edge cases to consider. Probably students would need to be assigned at the beginning of the course and this could not be changed later on (though students could be added to a group). We would also need to have a way to alert instructors to any group assignments that have too many comparisons for the number of groups that exist.

**Comment by andrew-gardener** [comment]
Should we display information to students within ComPAIR about their group and team mates or should the instructor handle informing students about this fully outside of ComPAIR? (if within ComPAIR there are several considerations around handling information we currently keep anonymous between students) 

When viewing answers, should students see the group's name or an anonymous name (like how we handle student display name. ex: Group_12345678) for author?




If its anonymized or not shown within ComPAIR, instructors would need to inform students outside of the tool so they can do group work together.

**Comment by lenglund** [comment]
I am fine to have communication re: teams handled outside ComPAIR (start simple). I think to use the group name is also fine, as this will could be equally anonymous (e.g., "Group 1").

**Comment by lenglund** [comment]
Picturing this as part of the assignment details area of the form. Not sure which approach is better: 1) disable selecting this if no groups are set but to provide a clear message that to enable , the instructor needs to go to <link> (to manage users) and set up groups or 2) enable selecting this but if no groups are set provide contextual access (to the manage users page in a modal?) with clear direction about how to set up groups...?

**Comment by lenglund** [comment]
Sounds good. Can we at least tell them the # of groups? A couple of screenshots to demonstrate.

Before checking:
![unchecked-groups](https://user-images.githubusercontent.com/6118592/41481407-aa8855b4-7086-11e8-965d-07e128692a34.png)

After checking:
![checked-groups](https://user-images.githubusercontent.com/6118592/41481409-adc7d1a0-7086-11e8-852f-6d9d4d54abd9.png)

Then maybe for the comparisons #:
![group-comparisons](https://user-images.githubusercontent.com/6118592/41482010-00b01de4-7089-11e8-8888-b9797d225811.png)

Though at a certain point, maybe it doesn't make sense to show this last info box, i.e., 10 or more comparisons are available? I'm not sure on this point...

**Comment by lenglund** [comment]
I'm assuming we can check and disable group switching on the Manage Users screen for group-assigned users after a group assignment has been run? So anyone not in a group can be added to an existing group, but anyone already in a group is locked in. Will also need to apply this logic to the bulk edit option, so users in groups can't be bulk changed either. (Do we want to prevent adding new groups as well? Probably not, but that's an option there too.)

**Comment by andrew-gardener** [comment]
> I'm assuming we can check and disable group switching on the Manage Users screen for group-assigned users after a group assignment has been run? 

This can be added. The way I've built it so far is that groups cannot be deleted after an answer exists for that group (note that there isn't any way in the ui to actually delete groups right now).

I think we can do something similar for locking students into groups as well. Locking them in when the first group assignment starts comparing also works. I guess that

I agree that I don't think we need to lock creating new groups at any time.

My only concern with locking students into groups is real world group classroom/group dynamic issues that would require splitting up or shuffling groups but that is likely to edge case for the first implementation.

**Comment by lenglund** [comment]
Yes, good points on the edge cases here. I agree start without worrying about group shuffle and see if it becomes an issue. For the # logic, maybe we start the text with "Unless you intend to add instructor/TA answers, this number should not exceed..."? And still allow entry of too high a #?

**Comment by andrew-gardener** [comment]
second part to be completed later

**Comment by lenglund** [comment]
Will open a research-based request separately.
