### ISSUE TITLE
Replace browser history when saving answer drafts

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/compair#615]
Noticed a usability tester running into this.

Saving an answer draft will redirect the user to the 'edit answer' screen. 

If a user goes back in browser history at this point, they will get a warning and be on the 'new answer' screen.

Instead, we would replace the browser history entry for the 'new answer' screen with the 'edit answer' screen so when they click back/forward it no longer goes to the 'new answer' screen.

**Comment by lenglund** [comment]
Good catch! This is why I like having observers - I saw the error but didn't catch why it happened. Thanks!

**Comment by kitsook** [comment]
@andrew-gardener @lenglund  When a user click on the back button after "Save Draft", showing the same "edit answer" page seems to be confusing.  The user might think nothing happened and he is still stuck on the same page.

Does it make more sense to go back to the page before the answering page?  Any thoughts?

Technically, should be able to do that by also calling `$location.replace()` when changing the path to the edit page

**Comment by lenglund** [comment]
Good point. I vote for going to the page before the answering page

**Comment by andrew-gardener** [comment]
@kitsook Yes using `$location.replace()` was the plan (sorry if my initial message wasn't clear on this)
