### ISSUE TITLE
ComPAIR - ability to hide student email addresses and UBC CWLs from instructors

### ISSUE THREAD

**Issue by timkato** [ubc/compair#618]
ComPAIR exposes student email addresses to instructors as well as CWLs. I understand in general instructors aren't supposed to have visibility into student email addresses. From my read of UBC privacy documentation, we should only expose this information if it is actually needed for ComPAIR to work and be used in a course. As I understand ComPAIR, neither of these pieces of information is needed by the instructor so we should avoid exposing them.

**Comment by andrew-gardener** [comment]
We should hide emails and CWL (/any third party login unique identifier) from instructors.
This effects profile page, edit user forms, class list, and export users
