### ISSUE TITLE
Organize students by last name, first name on "Comparisons" tab

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#619]
A student who was a TA for a course using ComPAIR this summer wisely pointed out that grading is most often done using student last names. Her use of ComPAIR was hindered by the way the "Comparisons" tab currently organizes student work by first name. This tab should have the headings read "Doe, Jane" instead of "Jane Doe" and be alphabetized accordingly.

(Also wondering if we should consider this for instructors/TAs in how we display drop-down lists? Or assume Chosen select negates this issue?)

**Comment by andrew-gardener** [comment]
I'll try changing the drop downs as well and we can undo if it looks bad (I think it would improve it though)
