### ISSUE TITLE
Add sorting/filtering options for course screen

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#623]
Allow students to sort assignments by:
- [x] Upcoming due date
- [x] Assignment start date (current default)

Allow students to additionally filter assignments by:
- [x] Drafts saved (answers and/or comparisons)
- [x] Feedback received

**Comment by lenglund** [comment]
Also consider a countdown for days remaining on assignments that are due.

**Comment by wynnset** [comment]
@lenglund / @andrew-gardener is there a place where we are using similar sorting on the site? I wanna make sure it's visually consistent with everything else.

**Comment by andrew-gardener** [comment]
@wynnset assignment screen has multiple way of sorting/filtering answers

**Comment by wynnset** [comment]
@lenglund / @andrew-gardener need some clarification:
- What does the "Instructor posted on dates" sort order mean? What would that sort on?
- The current sort order is by answer start date (desc) and created date (desc). Are we getting rid of this? 
  - If yes, which one would be the default sort order? 
  - If no, what should this sort order be called?
- Can you expand on "Also consider a countdown for days remaining on assignments that are due"? Where do you want to add this in?

Thanks in advance

**Comment by lenglund** [comment]
1) The current sort order would be the posted on date
2) So yes keep this one and use as the default and call something like "Posted On Date"
3) Let's discuss in the next meeting
