### ISSUE TITLE
Add state and UI change for comparison draft

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#624]
We want to enable and implement changing "Compare Pairs" buttons to "Finish Comparing" when a draft has been saved.

**Comment by andrew-gardener** [comment]
@lenglund Should we also change the button to `Self-evaluate` and `Finish Self-evaluation` when the user is self-evaluating (currently will still say `Compare Pairs`)

**Comment by lenglund** [comment]
Good question. For now, I think we are treating the self-eval as part of comparing (i.e., it is another "round"/"comparison"). In that case, probably keeping the button as "Compare Pairs" / "Finish Comparing" (depending on self-eval draft state) is fine.
