### ISSUE TITLE
Instructor is not able to submit multiple student answers

### ISSUE THREAD

**Issue by xcompass** [ubc/compair#633]
> I was testing the ability to submit late student assignments and it seems like I"m only able to do it once. I did it for one student, but the second time I try I get the error "Answer not updated, answer has already been submitted" (screenshot attached).

> However, when I go an check her answer, it doesn't exist (screenshot attached). It worked fine for the first student, but not this student.  

> The issue resolved itself after logging out and logging back in. I wonder if it's a cookie issue or something.  Each time I did it, I had to log out and log back in.

**Comment by xcompass** [comment]
The issue is most likely caused by a variable not being reset properly.

**Comment by kitsook** [comment]
Cannot simulate the case.  The described flow works fine in both production and locally (with latest master source or commit `5733758f`).  @xcompass will inform the instructor.  Closing the issue.
