### ISSUE TITLE
Switch delete confirmation to more customizable dialog

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#634]
Enable customization of button text and focus. Ideally we repeat action in buttons vs. just yes/no and have in focus the action that is least destructive (in this case, cancel).

**Comment by kitsook** [comment]
We could consider something similar to [Bootstrap Confirmation](http://bootstrap-confirmation.js.org/).  The popover will be displayed nearby.  Labels and buttons are customizable.

**Comment by xcompass** [comment]
could also consider Angular Material

**Comment by wynnset** [comment]
Bootstrap Confirmation does not seem to be very mobile-friendly, so I'd say Angular Material might be a better choice. That said, I'm not sure if we want to add a whole library just to have a pop-up confirmation (thinking performance here). I was considering just using a version of our own uibmodal.
