### ISSUE TITLE
Consistently apply form field feedback - instructors/admins

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#635]
Add inline error reporting for forms:

- [x] Course form
- [x] Duplicate course form
- [x] LTI consumer form
- [x] Report form
- [x] User form
- [x] Assignment form (also: “Select a default criterion -> Select one of your default criterion”,  default comparison/self-eval dates, practice pair does not include feedback, #880)
- [x] LTI course selection form
- [x] Login form
- [x] Student impersonation form

**Comment by lenglund** [comment]
I would also be in favour of inline error feedback, i.e., highlighting for users the invalid fields and how to fix them.

**Comment by wynnset** [comment]
@lenglund can you please expand on this? It sounds vague and so not actionable. Where is this issue happening? I see that, for example, when we are in Edit Course screen, it does highlight the fields that are required.

**Comment by lenglund** [comment]
Just a matter of testing the form required fields in their empty state and seeing which ones don't highlight, e.g., grade weights. We can discuss in next meeting.

**Comment by andrew-gardener** [comment]
remove current highlighting and add inline error messages, etc

**Comment by lenglund** [comment]
Hi @kitsook, thanks again for your help with the tests. This issue is now ready for review in the 635-inline-form-feedback branch.
