### ISSUE TITLE
Change status bar UI

### ISSUE THREAD

**Issue by wynnset** [ubc/compair#640]
Proposed changes for the status bar:

![compair-revised-status-bar](https://user-images.githubusercontent.com/8981258/32810692-faffdfcc-c950-11e7-8903-a77f3ecc223f.png)

Here are a few things that are different:
- Admin functions (edit, delete, duplicate) are displayed as icons on their own side
- There's a new status bar for the student to understand how much they have "progressed" in finishing their assignment, along with a status to the side. The letters in each status bar segment represent either "A" for "Answer", "C" for "Compare", or "S" for "Self-evaluate". In this case, the assignments have 3 compares, so there are 3 "C" segments. We can add a tooltip so the student can see what each of those segments mean upon hovering over them.
- The status is shorter and just focuses on what the student needs to know. In the example above: 
  - The first assignment is fully completed (student can take no action - checkmark assures them they are "done" and there is nothing else to do)
  - The second one is not completed, but the student still has time to complete it (student should take action - time is of the essence)
  - The third one is not completed, and the comparison period has passed (student can take no action - X indicates they did something wrong)

Tasks:
- General discussions about the feasibility of these changes
- Decide on scope (should we do something similar for homepage, assignment page, etc.)
- Discuss how these changes relate to the findings from the last round of usability testing
- Test new UI with users to get feedback 
- Implement changes as necessary

**Comment by lenglund** [comment]
peerScholar takes an interesting multi-layered approach to this same issue worth considering:

![peerscholar](https://user-images.githubusercontent.com/6118592/38058619-602269e6-3298-11e8-8a6e-7fda8e6e5f8d.jpg)

**Comment by andrew-gardener** [comment]
@lenglund how does it look with a smaller screen? (is it responsive?)

**Comment by wynnset** [comment]
This is interesting @lenglund thanks for sharing it. I think we can take some hints from this. I'll include that in the next version I come up with once I'm back on this task. I'm also interested to know how it looks on mobile.
