### ISSUE TITLE
Datepicker date constraints are not working

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#641]
Dates outside the constraints should not be select-able.

**Comment by kitsook** [comment]
@lenglund Want to check with you on the constraints to be enforced. e.g. for the assignment start date datepicker, there is a  constraint (though not working at this moment) to make sure it is before the assignment end date.
```
max-date="datePickerMaxDate(date.aend.date, course.end_date)"
```
While it makes sense logically, enforcing it in the datepicker seems to be not that user friendly.

For example, if I am to create a new assignment today (Nov 30), the assignment period will be pre-filled for me as Dec 1 - Dec 8.  But if I wanted it to be Dec 11 - Dec 15 and the constraints are enforced, I will need to change the assignment end date before changing the start date (as Dec 11 is after Dec 8).

Does it make more sense to relax the constraints for assignment datepickers to be any date within the course period?  When user click "Save", the existing program logic will check and warn users for any start date vs end date issue.

**Comment by lenglund** [comment]
Good point. I think I'd rather we remove the pre-filled dates to start with and continue to use the constraint. It's clear from how instructors are using this so far that we can't assume anything about the dates (i.e., each assignment duration is very customized), so the pre-fill is not really a timesaver. Thx!
