### ISSUE TITLE
Incorrect message displayed about answering / comparing status

### ISSUE THREAD

**Issue by kitsook** [ubc/compair#651]
With the current master source `89b991b`, incorrect assignment status shown.  During answering period and before the student inputting answer, the assignment status is shown as `You missed answering and comparing`.

When the student answered the assignment but before the comparison period starts, the assignment status is shown as `You missed comparing`.

**Comment by kitsook** [comment]
https://github.com/ubc/compair/blob/89b991bd7f623c3607bc440b3595b743f20c5a01/compair/static/modules/course/course-assignments-partial.html#L139-L143

https://github.com/ubc/compair/blob/89b991bd7f623c3607bc440b3595b743f20c5a01/compair/static/modules/assignment/assignment-view-partial.html#L45-L49

**Comment by wynnset** [comment]
@lenglund I guess the way to fix this is to see if the answer / compare due date is in the past (compare it with the current time). @andrew-gardener is moment() a reliable way of checking the current time?

**Comment by andrew-gardener** [comment]
you can also use `assignment.available` (should be true when `answer_start <= now`)

**Comment by andrew-gardener** [comment]
There is also `assignment.after_comparing` 
Can consider adding new `assignment.after_answering`

**Comment by wynnset** [comment]
Another issue - if there's a gap between the answer due date and the compare start date, it displays "Scheduled for [answer start date]", which is not very helpful to the instructor. I think in a case like that, we should display something like "Comparing scheduled for [compare start date]"

**Comment by wynnset** [comment]
I've implemented a change to the commit in #643 that would fix this.

**Comment by andrew-gardener** [comment]
Closed in #643
