### ISSUE TITLE
Make clear in UI for assignments that comparison participation can be partial

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#656]
i.e., that students get partial credit based on the number of comparisons completed, so it will be a percentage of the weighted percentage

**Comment by wynnset** [comment]
@lenglund can you please state:
- Exactly what the wording should be 
- Where it should appear
- Whether there are any conditions for this
- Who it should be displayed to

**Comment by lenglund** [comment]
No worries on this one; I assigned to myself and will update.

**Comment by lenglund** [comment]
Added in 96d2d242faf0e5489cb8a024b6e1f07e6d9648fa
