### ISSUE TITLE
Attachment still linked with answer after removal

### ISSUE THREAD

**Issue by kitsook** [ubc/compair#676]
Steps to recreate the issue:
- create a new answer
- select a file to attach
- click "remove" to remove the attached file
- type in the answer and save

When viewing the answer, the file is still attached to it.

The `reset` function in attachment service is returning a function
https://github.com/ubc/compair/blob/966729f2db4041d04efa8d64f88c1529d7cf78f5/compair/static/modules/attachment/attachment-module.js#L273-L277

So calling it in `$scope.resetFileUploader` is not actually resetting it
https://github.com/ubc/compair/blob/966729f2db4041d04efa8d64f88c1529d7cf78f5/compair/static/modules/answer/answer-module.js#L190-L198

Needs to be `(answerAttachService.reset())()`

**Comment by andrew-gardener** [comment]
can we instead change reset function in both `attachService` and `answerAttachService` to 
```

    var reset = function() {
        file = null;
    };
```

change `$scope.resetFileUploader = answerAttachService.reset();` to `$scope.resetFileUploader = answerAttachService.reset;` in `answer-module.js`

and change `$scope.resetFileUploader = attachService.reset();` to `$scope.resetFileUploader = attachService.reset;` in `assignment-module.js`

**Comment by andrew-gardener** [comment]
Also I'm moving this to 1.1.2
