### ISSUE TITLE
Add FAQ to support site

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#684]
See instructor interview notes as starting point

**Comment by lenglund** [comment]
> Can I use this for grading? How?
> How many rubrics (criteria) are best?
> How should I design a rubric?
> What should I give to students (instructions/rubrics)?
> What discipline or kind of assignment is this best for?
> What should I grade on?
> When / how often should I use it in a term?
> Where is it hosted (FIPPA)?
> What support is available?
> Is it anonymous?

**Comment by lenglund** [comment]
Also more examples

**Comment by andrew-gardener** [comment]
Talk to Tim

**Comment by lenglund** [comment]
Reference (and request updates):
https://isit.arts.ubc.ca/compair/

**Comment by andrew-gardener** [comment]
@lenglund this was completed with #813 correct?

**Comment by lenglund** [comment]
Yes!
