### ISSUE TITLE
Prevent students from editing LTI-imported critical details

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#685]
Instructors don't want students changing: first name, last name, or student number. These are the primary identifiers for grading. Students should be able to see this information and ask for correction, and instructors/admins should still have access to edit this.

**Comment by andrew-gardener** [comment]
- [ ] Need to overwrite first name, last name, and student number on lti launch and CAS login
- [ ] Need to add a new field to lti_consumer for storing which launch field holds to student number 
- [ ] Need to add a new field to lti_user to store the launch student_number (just for book keeping)
- [ ] Need to add a new environment variable storing the CAS attribute field that holds the student number
- [ ] Need to add a new environment variable which indicates if first name, last name, and student number are editable by students (default is allow but we will disallow in staging/prod)

**Comment by andrew-gardener** [comment]
@lenglund @xcompass there was discussion before on blocking students from changing their display name (since some changed it to their own name, etc). We could also lock these down at the same time if that is still desired
