### ISSUE TITLE
Break out self-evaluations as a separate step

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#687]
Right now, we treat self-evaluations as an "add-on" for comparisons. Instructors are interested in using this in a more robust way, in particular to encourage students to reflect on the feedback they receive. So having the option for self-evaluations to happen at a later stage in the overall process.

This requires:
- [x] On the back end, adding separate start and end dates for self-evals
- [x] On the back end, allowing for customize-able instructional text (so instructors can write based on their use case: compare to the answers you've seen, reflect on feedback you've received, etc.)
- [x] On the front end, removing self-evals as an add-on from the assignment form
- [x] On the front end, adding a new part of the assignment form for setting up self-evals - a new fieldset entirely, with optional start/end dates (default = self-eval is available after you finish comparing, no end date) and optional instructional text (default something generic, e.g., "Now write an evaluation of your own answer based on what you've read in completing this assignment.")
- [x] On the front end, changing action buttons/links from "Compare Pairs/Finish Comparing" to "Self-Evaluate/Finish Evaluating" for the self-eval step

Something else we might want to consider is having a checkbox for the instructor to explicitly select if the self-eval is to evaluate based on other answers or peer feedback. This could then dictate if we show/link to the student's completed comparisons or received feedback when they are on the self-eval screen.

**Comment by wynnset** [comment]
@lenglund / @andrew-gardener regarding the actual logic changes, I have a couple of questions:
1. Currently, students can only do self-eval if they have completed all their comparisons. 
  a. Do we want this logic to stay in place? Or should they still be able to self-eval even if they have not completed all their comparisons? 
  b. How would this logic change if the comparison period has ended? 
  c. How would this logic change in the case where there is no self-eval date range specified (but self-eval is enabled)? (Assuming fall back to existing logic in this case)
2. What are the constraints on these dates? 
  a. I'm assuming self-eval start date has to be after comparison start date. 
  b. Could the self-eval start date be before the comparison end date? 
  c. Could the self-eval end date be before the comparison end date? 
3. What's the logic if there is no self-eval end date defined? Can they self-eval until the course end date?

Thanks in advance

**Comment by andrew-gardener** [comment]
> 2a) The only constraint I suppose would be start date has to fall after the answer end date and end date has to fall before course end date (if one exists?). This means self-eval could come before, during, or after comparisons. What do you think @andrew-gardener? Am I overlooking complexities or other logic here?

This sounds fine to me

> How do we handle entering comparison start/end date? I think we require neither or both. Suggest the same approach here.

We currently require neither or both for start/end date. 



So that would mean that:
- self-eval with no start/end date: self-eval can be completed any time after comparisons completed (self-eval button only appears after comparisons completed).

Currently students are automatically redirected to self-eval after comparisons completed. I think we'd still want this to happen.

- self-eval with start/end dates: self-eval can only be completed during self-eval period (button only appears between start and end dates).

I assume when there is a self-evaluation period we would **not** want to automatically redirect to self-eval after comparisons are completed at all (even if it could be completed afterwards).
