### ISSUE TITLE
Clean up downloadable reports

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#689]
Based on instructor feedback:

- auto-replace "-" character when it starts a piece of written text (students are using this as a bullet point and it causes problems when opening the file in Excel, since this looks like a formula)
- remove extraneous white space in written text
- always include three core columns: Last Name, First Name, Student Number
- trim decimal places with scores to a more reasonable (easier to read) number (e.g., 2 places?)
- remove score-by-criterion column (this is no longer relevant, right?)
- call score simply "Answer Score" (not "percentage score")
- "Basic Participation Report" should include participation grade column
- "Basic Participation Report" should include answer text and URL for any attachments (two separate columns)
- "Basic Participation Report" should use more similar format to other participation report, with columns: Last Name, First Name, Student Number, Participation Grade, Answer, Answer Attachments, Answer Score, Evaluations Submitted, Evaluations Required, Self-Evaluation Submitted, Feedback Submitted
- "Participation Report for Research Teams" should change column "Replies Submitted" -> "Feedback Submitted"
- in "Compiled Peer Feedback Report", add word or character count column for each piece of feedback (whichever is easier) and label as such

**Comment by lenglund** [comment]
Would be nice too if the research report could include any deleted answers and columns for if/when the answer was deleted and if/when the answer was edited.

**Comment by kitsook** [comment]
>* trim decimal places with scores to a more reasonable (easier to read) number (e.g., 2 places?)

The gradebook on assignment page is rounding the Answer Score and Participation Grade to nearest integer (i.e. 0 decimal places).  Will do the same in reports.

![image](https://user-images.githubusercontent.com/13360325/42592262-d54d2550-84fd-11e8-8a1a-7c2bb809b6c5.png)

**Comment by lenglund** [comment]
The scores are different from the normalized percentages though, so I think we can keep a couple of places.

**Comment by lenglund** [comment]
A fair point. Let's maybe do "Feedback Submitted (During Comparisons)" and "Feedback Submitted (Outside Comparisons)", but maybe not include the second column if the instructor hasn't enabled this kind of feedback (so it doesn't create confusion when every student has a 0)? Not an issue if easier to just include all the time, though...

**Comment by kitsook** [comment]
I would suggest to keep the number of column fixed.  Easier to further process the CSV with Excel marco or other programs.

So there will be three feedback count columns:
- `Self-Evaluation Submitted`: self-evaluation only
- `Feedback Submitted (During Comparisons)`: feedback giving during comparisons
- `Feedback Submitted (Outside Comparisons)`: both public and private feedback
