### ISSUE TITLE
Consistently display student names for grading

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#690]
When instructors see student names in the UI, show them as "FirstName LastName (StudentNumber)" or "LastName FirstName (StudentNumber)" to help with grading. For all metadata areas where this appears on comparisons tab.

**Comment by andrew-gardener** [comment]
@lenglund just to confirm what labeling is currently used

Assignment Screen
- Answers tab
	- answer author label. currently: "DisplayName (FirstName LastName)"
	- feedback comment author label. currently: "displayname (FirstName LastName)"
        - user search box. currently: "LastName, FirstName"
- Comparison tab
	- user section heading. currently: "LastName, FirstName"
	- answer author label. currently: "FirstName LastName"
	- comparison heading label. currently: "FirstName LastName"
	- self-evaluation author label. currently: "FirstName LastName"
        - user search box. currently: "LastName, FirstName"
- Participation tab
	- has table columns for DisplayName, FirstName, and LastName
        - user search box. currently: "LastName, FirstName"

Just a couple of questions:
- Do we want to change the labeling for the answer screen?
- Do we want to remove the displayname from the participation tab (in addition to adding a student number column)?
- User select boxes on all three tabs have "LastName, FirstName". Do we want to consider changing them to "LastName, FirstName (StudentNumber)" for students as well (instructors/tas would remain the same)?

**Comment by lenglund** [comment]
> Do we want to change the labeling for the answer screen?
My sense is no need, since this is a grading thing and folks who are grading are reporting they do so from the Comparisons tab (which we'll probably rename if we go forward with the grading request). Updated issue desc.

> Do we want to remove the displayname from the participation tab (in addition to adding a student number column)?
Fine with this if it's getting too crowded with the student number column.

> User select boxes on all three tabs have "LastName, FirstName". Do we want to consider changing them to "LastName, FirstName (StudentNumber)" for students as well (instructors/tas would remain the same)?
Good call I think. (And the searches and user section heading should remain with last name first.)

All good questions, thanks!
