### ISSUE TITLE
Instructor labels not displayed on assignment screen

### ISSUE THREAD

**Issue by kitsook** [ubc/compair#699]
https://github.com/ubc/compair/blob/966729f2db4041d04efa8d64f88c1529d7cf78f5/compair/static/modules/assignment/assignment-view-partial.html#L182

should be 

```
<em>{{instructorLabel(answer.user_id)}} Response</em>
```

**Comment by lenglund** [comment]
Does this impact 1.1? Should we push in 1.1.2 instead?

**Comment by kitsook** [comment]
Checked that the issue was introduced on master branch only.  1.1.2 is not affected.
