### ISSUE TITLE
LocalStorage not initialized properly

### ISSUE THREAD

**Issue by kitsook** [ubc/compair#710]
`session-service` intended to cache user and permission information as session data. But  the data is stored in Local Storage instead of Session Storage.

There are two `myApp.config` calls defined in `compair-config.js`. That makes the `localStorageService` initialized before proper configuration is set in the second call.  So:
- prefix of the key used is the default `ls` instead of `ComPAIR`
- data is stored in `localStorage` instead of of intended `sessionStorage`

https://github.com/ubc/compair/blob/9683b812753fb71604a40fcea612ec93b40bd925/compair/static/compair-config.js#L265-L269

https://github.com/ubc/compair/blob/9683b812753fb71604a40fcea612ec93b40bd925/compair/static/compair-config.js#L698-L705

**Comment by andrew-gardener** [comment]
Taking over since I need to fix this for the LTI certification

**Comment by kitsook** [comment]
Notes for further investigation.  Merging the two `myApp.config` sections may resolve the issue, but only if the `setPrefix` etc calls are placed before `RouteResolvesProvider.$get()`.
