### ISSUE TITLE
Only one comparison shown under "Your Comparisons"

### ISSUE THREAD

**Issue by kitsook** [ubc/compair#720]
Problem with the current master branch at 49fa5ff.  Under the "Your Comparisons" tab, only one comparison is shown even when the student completed multiple comparisons.

Seems to be suppressed by CSS.

https://github.com/ubc/compair/blob/49fa5ff2fadc0d58872f6140ce50d90304bd738c/compair/static/less/assignment.less#L201-L203

![image](https://user-images.githubusercontent.com/13360325/36928559-aa26f816-1e3b-11e8-8426-f088fe7963bc.png)

**Comment by kitsook** [comment]
@andrew-gardener The change was made in 2dedcb2bab and merged into master.

https://github.com/ubc/compair/commit/2dedcb2babeb7bf45d93860986bd3262fe37262e#diff-1f1f7f86abff2b5e6557cf962aff091e

Branch 1.1.4 is not affected

https://github.com/ubc/compair/blob/release-1.1.4/compair/static/less/assignment.less#L203-L222

**Comment by andrew-gardener** [comment]
@kitsook I noticed so I changed it back right away (github isn't showing that for some reason)
