### ISSUE TITLE
The answer modal dialog causes 100% CPU usage when displayed

### ISSUE THREAD

**Issue by kitsook** [ubc/compair#755]
Problem with the current master branch a196fda.  Browser takes 100% CPU when the answer modal dialog is displayed.

Steps to reproduce the issue:
- go to course page
- find an assignment with answer period in progress or in the future (i.e. `answer_end` is in the future)
- click the "Answer" button to open the dialog box for answering
- browser will cause 100% CPU usage

Initial technical analysis:
- the course page has a filter on the assignments, which will be triggered in every `$digest`
https://github.com/ubc/compair/blob/a196fda1f32b0187c7d3771b9077197085399577/compair/static/modules/course/course-assignments-partial.html#L66-L67
- the answer form has a timer on it to monitor the assignment end time `answer_end`.  That will trigger `$digest` every millisecond
https://github.com/ubc/compair/blob/a196fda1f32b0187c7d3771b9077197085399577/compair/static/modules/answer/answer-form-partial.html#L31-L34
- when the above two combined together, the `filter` and `orderBy` functions in `ng-repeat` will be called repeatedly as long as the answer dialog box is displayed, causing 100% CPU usage

**Comment by andrew-gardener** [comment]
https://siddii.github.io/angular-timer/ has an interval setting (default 1 millisecond). we could increase it to something like 200~500 millisecond
