### ISSUE TITLE
Move project site to `gh-pages` branch

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/compair#777]
Would reduce image size, isolate project site code, and we can change the effective url from `http://ubc.github.io/compair/site/` to `http://ubc.github.io/compair/` (we can add redirects for all `site/` pages so existing links/bookmarks will still work).

**Comment by lenglund** [comment]
Sounds good to me!

**Comment by andrew-gardener** [comment]
Alright, will move after you've the support site changes are finished
