### ISSUE TITLE
Suppress additional warnings when impersonating

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#822]
Can we make sure the warnings for creating a new comparison and self-evaluation are the same as #765 for answer, i.e., we don't tell instructors they can't load/view a comparison/self-evaluation from the student POV?

If possible, would be great to include in Version 1.2 release!

**Comment by kitsook** [comment]
The same warnings are used for creating comparison / self-eval.

![image](https://user-images.githubusercontent.com/13360325/44233812-bffd2600-a159-11e8-88e1-3030cfe6868e.png)

![image](https://user-images.githubusercontent.com/13360325/44233884-f20e8800-a159-11e8-8fd7-f6bcdd650855.png)

**Comment by lenglund** [comment]
Sorry, to be clear: I was hoping we would NOT show these warnings when the instructor merely _loads_ the page in the student view. Loading the page for answering, comparing, or self-evaluating should be an action that is fine for them to do (that's why we are providing a preview after all) and triggers no warning; it's when they want to save or submit that we would show this warning.

**Comment by kitsook** [comment]
Got it.  Let me check.

**Comment by kitsook** [comment]
Loading the page for new comparison is good.  No warning when impersonating.

Will add suppression to self-eval.
