### ISSUE TITLE
Locking group membership

### ISSUE THREAD

**Issue by kitsook** [ubc/compair#854]
(1) Revise the group locked message

On the classlist page, if the group membership is locked, instructors will see the message `One or more group assignments have started or completed their comparison period. You may no longer remove users from the group they are assigned to.`

However, [the current logic](https://github.com/ubc/compair/blob/05ef114f7038a6e95c069ace46d859e4c9ba7314/compair/models/course.py#L110-L123) is actually based on whether there exist a group assignment with comparison period started.

(2) On production, if there is an assignment with answering period ended yesterday and the comparison period implicitly starts today, the instructor can still change membership.  Similar case can't be reproduced locally with docker devstack. Possible case of timezone issue(?)

(3) While troubleshooting another issue, it was noticed that a course with group assignment comparison period starting at `2018-10-30 16:01:00` but the `activity_log` indicates the instructor was able to change group members (event = `GROUP_USER_CREATE`) between `2018-11-04 08:11:42` and `2018-11-04 08:14:36`

**Comment by lenglund** [comment]
The message is correct from what I read here. The "started or completed" refers to the comparison period. We could remove "or completed" for clarity?

**Comment by kitsook** [comment]
If the message is correct, we will modify the code logic.  Currently, the logic only locks the groups if there exists a group assignment with comparison period started already.

**Comment by kitsook** [comment]
Found the cause of issue (2) and (3).

The `group_locked` is a class property defined in ` __declare_last__`:
https://github.com/ubc/compair/blob/05ef114f7038a6e95c069ace46d859e4c9ba7314/compair/models/course.py#L110-L123

So the `datetime.datetime.utcnow()` criteria is not called dynamically when object property is read.  Instead, it is only called once when the class was first loaded.  That means the time used for filtering is incorrect.

Can be fixed to use sql function `func.utc_timestamp()` on-the-fly instead of a value from python `datetime.datetime.utcnow()`

**Comment by andrew-gardener** [comment]
@kitsook Thanks for figuring this out!

**Comment by kitsook** [comment]
Fixed in v1.2.3
