### ISSUE TITLE
Save draft answer not working for instructors

### ISSUE THREAD

**Issue by kitsook** [ubc/compair#860]
Steps to simulate:
- instructor login. open an assignment and click the Answer button to open the answer dialog box
- input text for the answer. click "Save Draft" button.  "Answer Draft Saved" displayed. click Cancel and close the dialog box. back to the assignment page
- instead of showing the "Finish Answer" button, the page shows the "Answer" button instead.  refreshing the page doesn't help. instructor cannot resume editing the draft.

The Save Draft function is working fine for students though.

Initial analysis:
- the save draft API call is diff between instructor and student. possibly due to xapi
instructor: /api/courses/**course_uuid**/assignments/**assignment_uuid**
student: /api/courses/**course_uuid**/assignments/**assignment_uuid**/answers/**answer_uuid**

- this makes the timestamps `modified` and `created` the same for instructor's draft (the answer is created in one api call).  on the other hand, a student's answer is updated during save draft and so the `modified` timestamp is revised

- the `Answer` model defines `saved` property by comparing the `modified` and `created` timestamp (if it is draft). so for a draft answer created by instructor, the `saved` property is always false
https://github.com/ubc/compair/blob/05ef114f7038a6e95c069ace46d859e4c9ba7314/compair/models/answer.py#L70-L72

- the `Assignment` api retrieves only "saved" draft answers 
https://github.com/ubc/compair/blob/05ef114f7038a6e95c069ace46d859e4c9ba7314/compair/api/assignment.py#L516-L529

**Comment by lenglund** [comment]
Noticed the inability to access drafts when I was working on another issue, but I assumed it was due to the fact that instructors could submit multiple answers. My suggestion is to drop the save draft option for the instructors, since the functionality really is student-specific IMO...

**Comment by kitsook** [comment]
A fix is included in PR #855
