### ISSUE TITLE
"Anonymize Answers" button not working in "All answers" tab

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#870]
Clicking the "Anonymize Answers" button in the "All answers" tab does not hide the hyperlinked user name anymore.

**Comment by kitsook** [comment]
Some issues related to the display name on the "All answers" tab:

- Comparable instructor answers incorrectly marked as "Student" in anonymized view:
![image](https://user-images.githubusercontent.com/13360325/52820083-e431b500-305f-11e9-85ed-adaeca6c620c.png)

- When switching between normal and Student View, the display names are cached.  Need to flush the AngularJS cache factories when starting / stopping impersonation.
