### ISSUE TITLE
Shorten required demo comparisons

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#879]
Change default demo assignment for best film to 1 comparisons before self-eval. (Doing 3 takes too long for just a demo.)

**Comment by lenglund** [comment]
Can this still happen by end of August please?

**Comment by kitsook** [comment]
Changed the demo data with commit 9534b93.  Will do a restart tmr to make it effective

**Comment by lenglund** [comment]
Thanks!

**Comment by kitsook** [comment]
Restarted the demo machines and the scheduled daily job refreshed the db.  Now the demo assignment only needs 1 comparison
