### ISSUE TITLE
Consistently apply form field feedback - students

### ISSUE THREAD

**Issue by lenglund** [ubc/compair#884]
Apply inline styling per #635. Should build on #707.

- [x] Answer form
- [x] Comparison form
- [x] Feedback form

**Comment by lenglund** [comment]
All tests have passed on this branch (884-inline-form-feedback). @kitsook - This is ready for review and can be reviewed along with #707, as this is branched from that branch. (Probably appropriate to cherry-pick for the pull request here as well?)

**Comment by kitsook** [comment]
@lenglund Created a [new branch](/ubc/compair/tree/cherry-pick-for-%23884-inline-form-feedback) and cherry picked the commits.  Also added some fixes in order to merge with changes already on master branch.

Please take a look and raise a PR for review.
