### ISSUE TITLE
How much time does it take for database to be created while running the app for the first time?

### ISSUE THREAD

**Issue by arukshagrover** [ubc/compair#885]

**Comment by kitsook** [comment]
You can run the command `python manage.py database create` to create the database.  It takes maybe a few seconds to complete. 

If you want to populate the db with demo data, you can run `python manage.py database create -s` instead.

You can refer to [README.md](https://github.com/ubc/compair/blob/master/README.md) for more details.

**Comment by arukshagrover** [comment]
I ran this docker-compose up -d and then docker exec -it compair_app_1 python manage.py database create. It gets stuck at this command and when I try to reach localhost,I get gateway timeout error. 
Also, I deployed the whole app to azure but there are javascript errors in it. Am I doing something wrong? Do I need to install some more packages to make it run?

**Comment by kitsook** [comment]
Have you checked if the database container is up?  Do you see the tables created?  Any error messages when you check the log (e.g. `docker-compose logs -f`)?

**Comment by kitsook** [comment]
@arukshagrover Are you deploying ComPAIR to Windows vm on Azure?  If so, you may want to check if the db container is running properly.  In the `docker-compose.yml` file, it mounts a volume for persisting db data:
https://github.com/ubc/compair/blob/c9e529909004d8ce73c3e6908bf3b64707ca95a4/docker-compose.yml#L10-L11

The syntax may cause problem on Windows machines.  You may need to change the syntax to something similar to this:
https://github.com/docker-library/percona/issues/42#issuecomment-364414206

**Comment by arukshagrover** [comment]
Hey, I am using Linux azure vm to run this app. I can access the database. 
Now, I want to make some changes to the code, what shall I do to make code changes, can I run it without docker?

**Comment by arukshagrover** [comment]
Also, I am trying to login in the app using credentials from user table in compair database. None of the credentials are working. I havent made any changes to login settings. Whats the best way to login in to the app for testing purpose?

**Comment by kitsook** [comment]
> Hey, I am using Linux azure vm to run this app. I can access the database.
> Now, I want to make some changes to the code, what shall I do to make code changes, can I run it without docker?

The easiest way is to run the containers with `docker-compose`.  The `docker-compose.yml` file mounts the host source code folder.  This way you can modify your code on host and the `app` container will pick up the changes automatically.

https://github.com/ubc/compair/blob/136eeafdd7a055527241bfa3f036b3e0a7058c6c/docker-compose.yml#L53-L55

You can also run the app without docker.  You may refer to the Dockerfile on what software you need to install (e.g. uwsgi).  Or, you can refer to the Linux setup guide:
https://github.com/ubc/compair/tree/master/deploy/linux_server

Setup guide of other env:
https://github.com/ubc/compair/tree/master/deploy
