### ISSUE TITLE
Urgent: what is the default username and password for user, student, administrator and instructor? 

### ISSUE THREAD

**Issue by arukshagrover** [ubc/compair#887]

**Comment by kitsook** [comment]
are you referring to demo data? the usernames are `admin2`, `admin3`, `instructor1`, `instructor2`, `student1`, `student2`... etc.  Password is `demo`.

The default admin is `root` with password `password`.

You may refer to the fixture definitions:
https://github.com/ubc/compair/blob/fe97368de7b881cf8396f39007ef67b8e5607f21/data/fixtures/__init__.py#L41

https://github.com/ubc/compair/blob/fe97368de7b881cf8396f39007ef67b8e5607f21/data/fixtures/__init__.py#L16
