### ISSUE TITLE
Allow Each Assignment to Use Different Group Setup

### ISSUE THREAD

**Issue by cyw11** [ubc/compair#899]
At the moment, all group assignments within a ComPAIR course uses the same groups.

For example, if an instructor have two group assignments, the group assignments will be using the same group set up.  The workaround to this is for the instructor to create a new ComPAIR course and set up the new groups there.

**Comment by lenglund** [comment]
Add to future ideas wiki: https://github.com/ubc/compair/wiki/Future-ideas
