### ISSUE TITLE
Option to add a round for judging a student's own answer against another

### ISSUE THREAD

**Issue by ionparticle** [ubc/compair#95]
From instructor:

"Some feedback I've received from the students suggests that having the final round be a comparison of their own assignment with somone's elses might be helpful. By comparing your own it becomes a genuinely reflective activity.

I seem to remember this was mentioned briefly in the meetings, but we might want to give it further thought. Perhaps ad it as an option the instructor can select while making the question."

I do remember this being brought up in the meeting. Where they'd like, for the very last judgement, for students to compare their own answers to another students (presumably one similar in score).

**Comment by lenglund** [comment]
If we are going forward with this, I suggest we use the same approach as the self-reflection and provide just one box that allows the user to reflect. The only difference from the self-reflection would be the user sees his/her answer will another answer (and the instructional text would obviously change). Thoughts?

**Comment by ionparticle** [comment]
Sounds good.

**Comment by lenglund** [comment]
A Physics student requested this in the surveys from 2016 W1 term.

**Comment by lenglund** [comment]
An alternate approach would be to give students a way to display each answer they previously compared during the self-reflection step.

**Comment by andrew-gardener** [comment]
Math instructor requested this. Request: 

```
Is it possible after, say, 5 comparisons to force the tool to display two 
specific documents (the assignment submitted by the user and the correct answer 
submitted by the instructor) instead of two random ones?
```

**Comment by andrew-gardener** [comment]
three things that we can add in the future
- list previous answers (student can open them in modal to view more info)
- compare against another answer (maybe similarly scored)
- compare against an instructor answer (generated in assignment screen like practice pair)

**Comment by lenglund** [comment]
On hold until we make changes to support #687.
