### ISSUE TITLE
Unicode in assignment text causes "Internal server error"

### ISSUE THREAD

**Issue by rikblok** [ubc/compair#959]
Adding a smiley 🙂 (and presumably other unicode) in the "Additional assignment information" when editing an assignment throws a scary red "Internal server error" message when trying to save.  Fortunately, nothing is lost and removing the unicode character allows to save.

But the user may not know why it fails to save and the error message isn't enlightening 😉

I'm using the version currently at https://compair.elearning.ubc.ca

**Comment by timkato** [comment]
@rikblok Thanks for reporting this! We have a fix in our test environment, we happen to be working on this through https://github.com/ubc/compair/issues/908 and intend to deploy to production before September (hopefully end of July)
Cheers,
Tim
